# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true # default
contact_links:
  - name: 💬 You would like to discuss
    url: https://github.com/Pandemonium1986
    about: Feel free to connect with me
