---
name: "GitHub Super-Linter"

on:
  workflow_call:
    inputs:
      validate-all-code-base:
        description: "GitHub Super-Linter validate all code base instead of new code"
        required: false
        type: boolean
        default: true
      default-branch:
        description: "GitHub Super-Linter default branch"
        default: main
        required: false
        type: string
    secrets:
      github-token:
        description: "GitHub Token"
        required: true

jobs:
  lint:
    name: "Gsl: Lint Code Base"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: "Init: Run checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Lint: Code Base"
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: ${{ inputs.validate-all-code-base }}
          DEFAULT_BRANCH: ${{ inputs.default-branch }}
          GITHUB_TOKEN: ${{ secrets.github-token }}
          LINTER_RULES_PATH: .
